apiVersion: apps/v1
kind: Deployment
metadata:
  name: kelompok-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-commerce
  template:
    metadata:
      labels:
        app: e-commerce
    spec:
      containers:
      - name: shop
        image: gcr.io/project_akhir/shop:latest
        ports:
        - containerPort: 80
